- name: Take a snapshot
  hosts: controle
  tasks:
    - name: Exécution script 
      script: /home/pipeline/controle/takeSnapshot.ps1 -machine {{ MACHINE }} -snapshot {{ SNAPSHOT }} -user {{ USER }} -password {{ PASSWORD }} -server {{ SERVER }}
