- name: Delete Snapshot 
  hosts: controle
  tasks:
    - name: Exécution script 
      script: /home/pipeline/windows/deleteSnapshot.ps1 -machine {{ MACHINE }} -snapshot {{ SNAPSHOT }} -user {{ USER }} -password {{ PASSWORD }} -server {{ SERVER }}
